Sing up
deco-sites/niivu-bank pull request #3
Opened 2024-02-25 20:17 UTC by gabrielMatosBoubee

2024-02-25 21:33 UTC, gustavo-mvp requested changes

2024-02-25 21:33 UTC, gustavo-mvp commented on loaders/actions/singUp.ts
erro ortografico: signup.ts

2024-02-25 21:33 UTC, gustavo-mvp commented on packs/actions/supabase/singUp.ts
> +  }
Retorna objetos, { error:  "" }

E nesse caso, acho que vale dividir as verificações para facilitar no frontend como exibir o erro: 
- "Sua senha tem que ter 8 caracteres bla bla bla"
- "Seu email não é válido"

No caso não precisa retornar a mensagem exata, mas pelo menos diferir quando é um erro no cadastro da senha ou do email.

2024-02-25 21:33 UTC, gustavo-mvp commented on packs/actions/supabase/singUp.ts
> +  const client = createClient(supaBase.url!, supaBase.token!);
Pq não criar o cliente no site.ts e colocar no state o client? Assim nos loaders voces não precisam criar o cliente em toda chamada, ele é criado apenas uma vez e voce reutiliza o mesmo.

2024-03-04 02:16 UTC, gabrielMatosBoubee commented
This PR continue here: #https://github.com/deco-sites/niivu-bank/pull/4

2024-03-04 02:16 UTC, closed without merging